### PR TITLE
Fix for express compression module not activating

### PR DESCRIPTION
**Pull request by hdf**
Fix for Issues:
#199
and
expressjs/compression#38

### CODE REVIEW

**Comment by indutny** [comment]
Looks great, but what if we'll try to fit it somewhere here: https://github.com/indutny/node-spdy/blob/master/lib/spdy/stream.js#L52 ? I think you could use `connection._spdyState.isServer && !state.associated` as a condition for it.

Thank you!

**Comment by hdf** [comment]
Why would it be better there?

**Comment by indutny** [comment]
Because you won't need to hot-patch the `req` object and it will be properly built by the io.js/node.js core itself.

**Comment by hdf** [comment]
I have no idea, what that means, but I will try. :)

**Pull request closed without merging**
